# Workflow name
name: Build
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Keystore file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "keystore.jks"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Bundle
          path: app/release/app-release.aab
          retention-days: 5